name: Build
'on':
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build and analyze
        env:
          GITHUB_TOKEN: 0ec24bf8-94cd-4e79-b1f1-00b50cb4c56c
          SONAR_TOKEN: 811c9a490983734401ba4e491eaefc8bfa7281de
        run: >-
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.projectKey=sunilswizy_workflows
          -Dsonar.login=811c9a490983734401ba4e491eaefc8bfa7281de
      
      - name: Trigger API
        if: ${{ success() }} # Only run this step if the previous step (Build and analyze) is successful
        env:
          API_URL: https://cf38-183-82-250-177.ngrok.io/api/restoreSonarQube
        run: |
          REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2)
          API_PAYLOAD="{ \"teams_id\": \"$REPO_NAME\" }"
          curl -X POST -H "Content-Type: application/json" -d "$API_PAYLOAD" $API_URL